// ============================================
// Hypertrophy Lab — Exercise Database
// ============================================
// 50+ exercises with primary/secondary muscle group tags

import { Exercise } from "@/types";

export const exercises: Exercise[] = [
  // ─── CHEST ───
  {
    id: "flat-barbell-bench-press",
    name: "Flat Barbell Bench Press",
    image: "/exercises/flat-barbell-bench-press.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Triceps",
    equipment: "Barbell, Flat Bench",
  },
  {
    id: "incline-barbell-bench-press",
    name: "Incline Barbell Bench Press",
    image: "/exercises/incline-barbell-bench-press.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Shoulders",
    equipment: "Barbell, Incline Bench",
  },
  {
    id: "dumbbell-flat-bench-press",
    name: "Dumbbell Flat Bench Press",
    image: "/exercises/dumbbell-flat-bench-press.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Triceps",
    equipment: "Dumbbells, Flat Bench",
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    image: "/exercises/incline-dumbbell-press.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Shoulders",
    equipment: "Dumbbells, Incline Bench",
  },
  {
    id: "cable-flyes",
    name: "Cable Flyes",
    image: "/exercises/cable-flyes.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Shoulders",
    equipment: "Cable Machine",
  },
  {
    id: "dips-chest",
    name: "Chest Dips",
    image: "/exercises/dips-chest.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Triceps",
    equipment: "Dip Station",
  },
  {
    id: "pec-deck-fly",
    name: "Pec Deck Fly",
    image: "/exercises/pec-deck-fly.jpg",
    primaryMuscle: "Chest",
    secondaryMuscle: "Shoulders",
    equipment: "Pec Deck Machine",
  },

  // ─── BACK ───
  {
    id: "barbell-row",
    name: "Barbell Row",
    image: "/exercises/barbell-row.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "Barbell",
  },
  {
    id: "pull-ups",
    name: "Pull-Ups",
    image: "/exercises/pull-ups.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "Pull-Up Bar",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    image: "/exercises/lat-pulldown.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "Cable Machine",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    image: "/exercises/seated-cable-row.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "Cable Machine",
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell Row",
    image: "/exercises/dumbbell-row.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "Dumbbell, Bench",
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    image: "/exercises/t-bar-row.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "T-Bar Machine",
  },
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    image: "/exercises/deadlift.jpg",
    primaryMuscle: "Back",
    secondaryMuscle: "Hamstrings",
    equipment: "Barbell",
  },

  // ─── SHOULDERS ───
  {
    id: "overhead-press",
    name: "Overhead Press",
    image: "/exercises/overhead-press.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Triceps",
    equipment: "Barbell",
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    image: "/exercises/dumbbell-shoulder-press.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Triceps",
    equipment: "Dumbbells",
  },
  {
    id: "lateral-raises",
    name: "Lateral Raises",
    image: "/exercises/lateral-raises.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Traps",
    equipment: "Dumbbells",
  },
  {
    id: "face-pulls",
    name: "Face Pulls",
    image: "/exercises/face-pulls.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Traps",
    equipment: "Cable Machine",
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    image: "/exercises/reverse-pec-deck.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Back",
    equipment: "Pec Deck Machine",
  },
  {
    id: "front-raises",
    name: "Front Raises",
    image: "/exercises/front-raises.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Chest",
    equipment: "Dumbbells",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    image: "/exercises/arnold-press.jpg",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Triceps",
    equipment: "Dumbbells",
  },

  // ─── BICEPS ───
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    image: "/exercises/barbell-curl.jpg",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "Barbell",
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    image: "/exercises/dumbbell-curl.jpg",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "Dumbbells",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    image: "/exercises/hammer-curl.jpg",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "Dumbbells",
  },
  {
    id: "incline-dumbbell-curl",
    name: "Incline Dumbbell Curl",
    image: "/exercises/incline-dumbbell-curl.jpg",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "Dumbbells, Incline Bench",
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    image: "/exercises/preacher-curl.jpg",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "EZ Bar, Preacher Bench",
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    image: "/exercises/cable-curl.jpg",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "Cable Machine",
  },

  // ─── TRICEPS ───
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    image: "/exercises/close-grip-bench-press.jpg",
    primaryMuscle: "Triceps",
    secondaryMuscle: "Chest",
    equipment: "Barbell, Flat Bench",
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    image: "/exercises/tricep-pushdown.jpg",
    primaryMuscle: "Triceps",
    secondaryMuscle: "Shoulders",
    equipment: "Cable Machine",
  },
  {
    id: "overhead-tricep-extension",
    name: "Overhead Tricep Extension",
    image: "/exercises/overhead-tricep-extension.jpg",
    primaryMuscle: "Triceps",
    secondaryMuscle: "Shoulders",
    equipment: "Cable Machine / Dumbbell",
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    image: "/exercises/skull-crushers.jpg",
    primaryMuscle: "Triceps",
    secondaryMuscle: "Shoulders",
    equipment: "EZ Bar, Flat Bench",
  },
  {
    id: "dips-tricep",
    name: "Tricep Dips",
    image: "/exercises/dips-tricep.jpg",
    primaryMuscle: "Triceps",
    secondaryMuscle: "Chest",
    equipment: "Dip Station",
  },

  // ─── QUADS ───
  {
    id: "barbell-squat",
    name: "Barbell Back Squat",
    image: "/exercises/barbell-squat.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Glutes",
    equipment: "Barbell, Squat Rack",
  },
  {
    id: "front-squat",
    name: "Front Squat",
    image: "/exercises/front-squat.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Core",
    equipment: "Barbell, Squat Rack",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    image: "/exercises/leg-press.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Glutes",
    equipment: "Leg Press Machine",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    image: "/exercises/leg-extension.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Core",
    equipment: "Leg Extension Machine",
  },
  {
    id: "walking-lunges",
    name: "Walking Lunges",
    image: "/exercises/walking-lunges.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Glutes",
    equipment: "Dumbbells",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    image: "/exercises/bulgarian-split-squat.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Glutes",
    equipment: "Dumbbells, Bench",
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    image: "/exercises/hack-squat.jpg",
    primaryMuscle: "Quads",
    secondaryMuscle: "Glutes",
    equipment: "Hack Squat Machine",
  },

  // ─── HAMSTRINGS ───
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    image: "/exercises/romanian-deadlift.jpg",
    primaryMuscle: "Hamstrings",
    secondaryMuscle: "Glutes",
    equipment: "Barbell",
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    image: "/exercises/lying-leg-curl.jpg",
    primaryMuscle: "Hamstrings",
    secondaryMuscle: "Calves",
    equipment: "Leg Curl Machine",
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    image: "/exercises/seated-leg-curl.jpg",
    primaryMuscle: "Hamstrings",
    secondaryMuscle: "Calves",
    equipment: "Leg Curl Machine",
  },
  {
    id: "stiff-leg-deadlift",
    name: "Stiff-Leg Deadlift",
    image: "/exercises/stiff-leg-deadlift.jpg",
    primaryMuscle: "Hamstrings",
    secondaryMuscle: "Back",
    equipment: "Barbell",
  },

  // ─── GLUTES ───
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    image: "/exercises/hip-thrust.jpg",
    primaryMuscle: "Glutes",
    secondaryMuscle: "Hamstrings",
    equipment: "Barbell, Bench",
  },
  {
    id: "cable-kickback",
    name: "Cable Kickback",
    image: "/exercises/cable-kickback.jpg",
    primaryMuscle: "Glutes",
    secondaryMuscle: "Hamstrings",
    equipment: "Cable Machine",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    image: "/exercises/glute-bridge.jpg",
    primaryMuscle: "Glutes",
    secondaryMuscle: "Hamstrings",
    equipment: "Barbell",
  },

  // ─── CALVES ───
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    image: "/exercises/standing-calf-raise.jpg",
    primaryMuscle: "Calves",
    secondaryMuscle: "Core",
    equipment: "Calf Raise Machine",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    image: "/exercises/seated-calf-raise.jpg",
    primaryMuscle: "Calves",
    secondaryMuscle: "Core",
    equipment: "Seated Calf Machine",
  },

  // ─── CORE ───
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    image: "/exercises/cable-crunch.jpg",
    primaryMuscle: "Core",
    secondaryMuscle: "Shoulders",
    equipment: "Cable Machine",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    image: "/exercises/hanging-leg-raise.jpg",
    primaryMuscle: "Core",
    secondaryMuscle: "Forearms",
    equipment: "Pull-Up Bar",
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    image: "/exercises/ab-wheel-rollout.jpg",
    primaryMuscle: "Core",
    secondaryMuscle: "Shoulders",
    equipment: "Ab Wheel",
  },
  {
    id: "plank",
    name: "Plank",
    image: "/exercises/plank.jpg",
    primaryMuscle: "Core",
    secondaryMuscle: "Shoulders",
    equipment: "Bodyweight",
  },

  // ─── TRAPS ───
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    image: "/exercises/barbell-shrug.jpg",
    primaryMuscle: "Traps",
    secondaryMuscle: "Shoulders",
    equipment: "Barbell",
  },
  {
    id: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    image: "/exercises/dumbbell-shrug.jpg",
    primaryMuscle: "Traps",
    secondaryMuscle: "Shoulders",
    equipment: "Dumbbells",
  },

  // ─── FOREARMS ───
  {
    id: "wrist-curl",
    name: "Wrist Curl",
    image: "/exercises/wrist-curl.jpg",
    primaryMuscle: "Forearms",
    secondaryMuscle: "Biceps",
    equipment: "Barbell / Dumbbells",
  },
  {
    id: "reverse-wrist-curl",
    name: "Reverse Wrist Curl",
    image: "/exercises/reverse-wrist-curl.jpg",
    primaryMuscle: "Forearms",
    secondaryMuscle: "Biceps",
    equipment: "Barbell / Dumbbells",
  },
];

// All unique muscle groups from the exercises list
export const muscleGroups: string[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Core",
  "Traps",
  "Forearms",
];

// Muscle group color mapping for badges
export const muscleGroupColors: Record<string, { bg: string; text: string }> = {
  Chest: { bg: "bg-red-500/20", text: "text-red-400" },
  Back: { bg: "bg-blue-500/20", text: "text-blue-400" },
  Shoulders: { bg: "bg-amber-500/20", text: "text-amber-400" },
  Biceps: { bg: "bg-purple-500/20", text: "text-purple-400" },
  Triceps: { bg: "bg-pink-500/20", text: "text-pink-400" },
  Quads: { bg: "bg-green-500/20", text: "text-green-400" },
  Hamstrings: { bg: "bg-emerald-500/20", text: "text-emerald-400" },
  Glutes: { bg: "bg-orange-500/20", text: "text-orange-400" },
  Calves: { bg: "bg-teal-500/20", text: "text-teal-400" },
  Core: { bg: "bg-cyan-500/20", text: "text-cyan-400" },
  Traps: { bg: "bg-indigo-500/20", text: "text-indigo-400" },
  Forearms: { bg: "bg-lime-500/20", text: "text-lime-400" },
};
